use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/tickets",
        "customerservice",
        "customerservice.tickets.admin.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/tickets/{ticketId}",
        "customerservice",
        "customerservice.tickets.admin.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/customer_services/tickets/{ticketId}",
        "customerservice",
        "customerservice.tickets.admin.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/tickets/{ticketId}/messages",
        "customerservice",
        "customerservice.tickets.admin.messages.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/customer_services/tickets/{ticketId}/messages",
        "customerservice",
        "customerservice.tickets.admin.messages.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/plugins",
        "customerservice",
        "customerservice.plugins.admin.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/customer_services/plugins/{pluginCode}/enablement",
        "customerservice",
        "customerservice.plugins.admin.enablement.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/channels/accounts",
        "customerservice",
        "customerservice.channels.admin.accounts.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/customer_services/channels/accounts",
        "customerservice",
        "customerservice.channels.admin.accounts.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/customer_services/channels/accounts/{accountId}",
        "customerservice",
        "customerservice.channels.admin.accounts.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/customer_services/channels/accounts/{accountId}/credentials",
        "customerservice",
        "customerservice.channels.admin.accounts.credentials.register",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/channels/auto_reply_rules",
        "customerservice",
        "customerservice.channels.admin.autoReplyRules.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/customer_services/channels/auto_reply_rules",
        "customerservice",
        "customerservice.channels.admin.autoReplyRules.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/customer_services/channels/auto_reply_rules/{ruleId}",
        "customerservice",
        "customerservice.channels.admin.autoReplyRules.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/customer_services/channels/auto_reply_rules/{ruleId}",
        "customerservice",
        "customerservice.channels.admin.autoReplyRules.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/channels/delivery_block_rules/catalog",
        "customerservice",
        "customerservice.channels.admin.deliveryBlockRules.catalog",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/channels/accounts/{accountId}/delivery_block_rules",
        "customerservice",
        "customerservice.channels.admin.deliveryBlockRules.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/customer_services/channels/accounts/{accountId}/delivery_block_rules",
        "customerservice",
        "customerservice.channels.admin.deliveryBlockRules.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/customer_services/channels/accounts/{accountId}/runtime/start",
        "customerservice",
        "customerservice.channels.admin.accounts.runtime.start",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/customer_services/channels/accounts/{accountId}/runtime/stop",
        "customerservice",
        "customerservice.channels.admin.accounts.runtime.stop",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/customer_services/channels/accounts/{accountId}/runtime/status",
        "customerservice",
        "customerservice.channels.admin.accounts.runtime.status",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
